config/routes.rb
Rails.application.routes.draw do

  resources :articles
  get "/ask_toc_request/:id" => "articles#ask_toc_request" 
  get "/ask_customize/:id" => "articles#ask_customize"
  get "/schedule_call/:id" => "articles#schedule_call"

  get 'report_types/index'

  get 'report_types/show'

  match "/report_back", :to => "reports#lolcat", :via => [:get]

  namespace :admin do
    resources :blog_rss_feeds
  end

  get "/rss-feeds" =>"home#rss_feeds"
  get "/rss/category/:id" => "home#get_rss_feed_of_category"
  get "/rss/report-types/:id" => "home#get_rss_feed_of_report_type"
  get "/rss/countries/:id" => "home#get_rss_feed_of_country"
  get "/rss/continents/:id" => "home#get_rss_feed_of_continents"
  get "/rss/regions/:id" => "home#get_rss_feed_of_regions"
  get "/rss/news-and-update" => "home#get_rss_feed_of_news_and_update"
  get "/rss/latest-reports" => "home#get_latest_reports"
  get "/rss/top-selling-reports" => "home#get_top_selling_reports"
  get "/rss/upcoming-reports" => "home#get_rss_feed_of_upcoming_reports"
  get "/rss/popular-categories" => "home#get_rss_feed_of_popular_categories"
  post "/show_side_panel_of_category" => "home#show_side_panel_of_category"

  post "/show_all_publishers" => "report_filters#show_all_publishers"
  post "/show_default_publishers" => "report_filters#show_default_publishers"
  post "/show_filter_reports" => "report_filters#show_filter_reports"
  get "/get_all_publishers" => "report_filters#get_all_publishers"
  get "/sort_publishers/:name" =>"report_filters#sort_publishers"
  post "/show_all_countries" => "report_filters#show_all_countries"
  post "/show_all_categories" => "report_filters#show_all_categories" 
  post "/show_all_continents" => "report_filters#show_all_continents"
  post "/show_all_regions" => "report_filters#show_all_regions"
  post "/show_selected_regions" => "report_filters#show_selected_regions"
  post "/show_selected_continents" => "report_filters#show_selected_continents"
  post "/reset_to_default_by_category" => "categories#reset_to_default_by_category"
  post "/new_report_enquiry" => "home#new_report_enquiry"
  post "/hdfc_secret" => "shopping_carts#hdfc_secret"
  post "/user_detail" => "shopping_carts#user_detail"
  post "blogs/post_comment" => "blogs#post_comment"

  resources :blogs, only: [:show,:index] do
    get 'blog_comments'
    collection do
      match "/category/:slug", :to => "blogs#blog_category",  :via => [:get, :post], :as => :blog_category
      match 'search' => 'blogs#search', :via => [:get, :post], :as => :blog_search
    end
  end
  get 'tags/:tag', to: 'blogs#index', as: :tag

  
  match 'blogs/by_year_and_month/:year/:month' => 'blogs#by_year_and_month', :via => [:get, :post], :as=> :blogs_by_year_and_month

  
  resources :user_sessions, only: [:new,:create,:destroy]
  post "/transaction/ccavRequestHandler" => "shopping_carts#ccavRequestHandler"

  match "/transaction/ccavResponseHandler" =>'shopping_carts#ccavResponseHandler', :via => [:get, :post]
  match "/transaction/cancel" =>'shopping_carts#cancel_transaction', :via => [:get, :post]
  resources :users, only: [:show,:new,:create]
  get 'signup' => 'users#new', :as => :signup

  root :to => 'home#index'

  get 'login'   => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
  get 'signout' => 'user_sessions#destroy', as: :signout
  match "about_us" =>'pages#about_us', :via => [:get]
  match "faqs" =>'pages#faqs', :via => [:get]
  resources :password_resets, :only => [:new, :edit, :update]
  resources :news_updates, :only => [:show,:index], :path => '/press-release'
  namespace :admin do 
    resources :blogs do
      collection do
        get "blog_logs"
        get "blog_log_detail"
      end
    end
    resources :advertisements
    match "/advertisements/:id/delete", :to => "advertisements#destroy", :via => ["delete"]

    resources :report_types
    match '/dashboard' => "dashboard#index", :via => ["get"], :as => :root
    match "/blogs/:id/delete", :to => "blogs#destroy", :via => ["delete"]
    match "/blog_rss_feeds/:id/delete", :to => "blog_rss_feeds#destroy", :via => ["delete"]
    resources :categories
    match "/categories/:id/delete", :to => "categories#destroy", :via => ["delete"]
    resources :publishers
    match "/publishers/:id/delete", :to => "publishers#destroy", :via => ["delete"]
    resources :pages
    resources :news_updates
    match "/news_updates/:id/delete", :to => "news_updates#destroy", :via => ["delete"]
    resources :reports do
      collection do
        match 'search' => 'reports#search', :via => [:get], :as => :search
        match 'search_reports' => 'reports#search_reports', :via => [:post]
        post :edit_multiple
        put :update_multiple
        post :upload_multiple
        post :save_position
      end 

    end

    match "report_labels" =>'reports#report_labels', :via => [:get, :post]
    match "deactive_reports" =>'reports#deactive_reports', :via => [:get, :post]
    match "upload_files" => 'reports#upload_files', :via => [:get, :post]
    match "sort_reports" =>'reports#sort_reports', :via => [:get, :post]
   

    match "/reports/:id/delete", :to => "reports#destroy", :via => ["delete"]
    resources :messengers
    resources :conversations, only: [:show,:create] do
       resources :messengers
    end
    resources :orders
    resources :subscribers, :only => [:index, :show]  do 
      collection do
        post :toggle_active
      end
    end
    resources :testimonials
    match "/testimonials/:id/delete", :to => "testimonials#destroy", :via => ["delete"]
    match "/newsletter_templates/:id/delete", :to => "newsletter_templates#destroy", :via => ["delete"]
    match "/subscribers/:id/delete", :to => "subscribers#destroy", :via => ["delete"]
    match "order_details" =>'orders#order_details', :via => [:get, :post]
    resources :enquiries do
      collection do
        match 'list'=>"enquiries#list" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#list_by_date" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#delete_list" ,:via=>[:get,:delete]
        post :edit_multiple
      end
    end
   
    match "/pages/:id/delete", :to => "pages#destroy", :via => ["delete"]
    match "/enquiries/:id/delete_contact_us", :to => "enquiries#delete_contact_us", :via => ["delete"]
    
    match "/enquiries/:id/delete", :to => "enquiries#destroy", :via => ["delete"]
    match "contact_us" =>'enquiries#contact_us', :via => [:get, :post]
    match "/admin_change_password" => "dashboard#change_password", :via => [:get, :post]

    resources :newsletter_templates do 
      collection do
        post :send_multiple
        post :delete_multiple
      end
    end

    resources :clients
    match "/clients/:id/delete", :to => "clients#destroy", :via => ["delete"]
  end

  match "/send_password" => "password_resets#send_password" , :via=>[:post]
  match "/update_password" => "password_resets#update" , via: [:patch]
  match "/upload_excelsheet" => "admin/reports#upload_multiple" , via: [:post]
  match "/upload_reports" => "admin/reports#upload_reports" , via: [:post,:get]

  resources :reports, only: [:show,:index]  do
    collection do
       match 'search' => 'reports#search', :via => [:get, :post], :as => :search
       get :get_all_reports
       get 'currency_section'
    end 
    get :reset_filterrific, on: :collection    
  end 

  resources :categories, only: [:show,:index]

  resources :regions, only: [:show,:index] do
    member do
      match "/country_wise/:country_id", :to => "regions#country_wise", :via => ["get"]
    end
    collection do
      get 'reset_filter'
    end
  end
  resources :messages, only: [:create]
  resource :shopping_cart, only: [:show,:create]
  resources :pages, :only => [:show]
  match "/remove_item" => 'shopping_carts#remove_item', :via => [:get, :post]
  post "reports/enquiry" => "reports#enquiry"
  post "reports/enquiry_link" => "reports#enquiry_link"

  get "/clear_cart" => 'shopping_carts#clear_cart'
  get "/load_add_to_cart" => "shopping_carts#load_add_to_cart"
  get "/load_place_order_items" => "shopping_carts#load_place_order_items"

  post "/add_to_cart" => "shopping_carts#add_to_cart"
  

  post "blogs/post_comment" => "blogs#post_comment"

  get "/manage_address"  => 'shopping_carts#manage_address'
  get "/checkout"  => 'shopping_carts#checkout'
  get "/place_order"=> 'shopping_carts#place_order'
  get "/paypal_order_cancel"=> 'shopping_carts#paypal_order_cancel'

  get "/buynow_paypal_cancel"=> 'shopping_carts#buynow_paypal_cancel'
  resources :customers
  match "/update_quantity" => "shopping_carts#update_quantity", via: "post"
  match "/update_user" => "users#update_user", via: "post"
  match "/change_password" => "users#change_password", :via => [:get, :post]
  match "/update_password" => "users#update_password", :via => [:get, :post]
  match "/create_user" => "shopping_carts#create_user", via: "post"
  match "/signin_user" => "shopping_carts#signin_user", via: "post"
  match "/create_customer" => "shopping_carts#create_customer", via: "post"
  match "/complete_order" => "orders#complete_order", via: "post"
  match "/complete_ccavenue_order" => "orders#complete_ccavenue_order", :via => [:get, :post]

  match "/ccavenue_transfer" => "orders#ccavenue_transfer" , via: "post"
  match "/new_user_ccavenue_transfer" => "orders#new_user_ccavenue_transfer" , via: "post"
  get "purchase_complete" => "orders#purchase_complete"
  get "purchase_cancel" => "orders#purchase_cancel"

  match "/express_checkout" => "orders#express_checkout", via: "post"
  match "/wire_transfer" => "orders#wire_transfer", via: "post"
  get "/charges" , :controller=>"charges", :action=>"create"
  match "/save_chat_user" => "messages#save_chat_user", via: "post"
  resources :orders do
    collection do
      post 'send_to_ccavenue'
    end
  end
  resources :charges, only: [:new,:create]
  resources :continents, :only => [:index, :show] do
    collection do

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :category_report_image, CategoryReportImageUploader
  mount_uploader :category_image, CategoryImageUploader
  mount_uploader :category_icon, CategoryIconUploader
  include Tree
  has_many :reports, :dependent => :destroy
  has_many :news_updates, :dependent => :destroy
  has_many :blogs, :dependent => :destroy, :class_name => "Admin::Blog"
  has_many :publishers, through: :reports
  has_many :country_reports, through: :reports
  has_many :countries, {:through=>:reports, :source=>:country}
  has_many :regions, through: :country_reports
  has_many :continents, through: :countries
  has_many :report_types, through: :reports
  extend FriendlyId
  friendly_id :name, use: :slugged
  before_save   :cache_ancestry
  before_update :cache_ancestry
  before_create :cache_ancestry 
  after_save :expire_cache

  def cache_ancestry
    self.name = self.name.strip     
  end

  def reports
    Report.where("category_id in (?)", self.subtree.pluck("id")) 
  end

  def publishers
    report_type_count = ReportType.search(:sql=>{:select=>"report_types.id"}).total_entries
    ReportType.search(:max_matches => report_type_count,:with=>{:category_ids=>self.subtree.pluck("id")})
  end

  def self.get_all_categories
    Rails.cache.fetch("all-categories") do
      Category.search(:sql => {:select => "id,slug,name,reports_count,category_icon as category_icon" }, :with => {:root_ancestry => 0},:order=>"category_name asc").to_a
    end
  end

  def self.options_for_select
    Category.roots.all.map { |e| [e.name, e.id] }
  end

  def expire_cache
    Rails.cache.delete("report_category_count")
  end

  def self.category_hash
    Rails.cache.fetch("category-hash") do
      category_count = Category.search(:sql=>{:select=>"categories.id"}).total_entries
      Category.search(:sql => {:select => "id,slug,name" }, :with => {:root_ancestry => 0},:per_page=>category_count).to_a.inject({}) {|i,n| i.merge({n.id => {:name => n.name, :slug => n.slug}})}
    end
  end

  def self.sphinx_get_child_ids(categories_ids)
    category_count = Category.search(:sql=>{:select=>"categories.id"}).total_entries
    Category.search(:with => {:root_ancestry => categories_ids},:sql=>{:select=>"id"},:per_page=>category_count).map(&:id)
  end

  def self.get_category_and_subcategory(categories_ids)
    category_ids = categories_ids
    category_ids.push(Category.sphinx_get_child_ids(categories_ids))
    category_ids.flatten
  end

  def self.recount_report_count
    all.each do |category|
      category_count = Category.search(:sql=>{:select=>"categories.id"}).total_entries
      category_ids = [category.id,Category.search(:with => {:root_ancestry => category.id},:sql => { :select => "id" },:per_page=>category_count).map(&:id)].flatten
      new_reports_count = Report.search(:with => {:upcoming => 0, :category_id => category_ids}, :sql => {:select => 'reports.id'}).total_entries
      category.update_attribute('reports_count',new_reports_count)
    end
  end

end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
  mount_uploader :report_type_image, ReportTypeImageUploader
  has_many :reports
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end
  
  def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id] }
  end

  def self.recount_report_count
    all.each do |type|
      new_reports_count = Report.search(:sql => {:select => 'reports.id'}, :with =>  {:upcoming => 0,:report_type_id => type.id}).count
      type.update_attribute('reports_count',new_reports_count)
    end
  end

  def self.report_type_list
    Rails.cache.fetch("all-report_types") do
      ReportType.select("id","name","slug","abbreviation","reports_count").order("name asc")
    end
  end

  # def self.set_latest_reports
  #   self.select(:id).each do |type|
  #     type.reports.update_all("latest_publisher_report = 0")
  #     latest_report = type.reports.order("case day when '' then str_to_date(CONCAT('01/',publish_month),'%d/%m/%Y') ELSE str_to_date(CONCAT(day,'/',publish_month),'%d/%m/%Y') END  DESC").
  #     limit(1).
  #     first
  #     latest_report.update_attribute("latest_publisher_report",true) if latest_report
  #   end
  # end

  def relevant_reports
    Rails.cache.fetch("relevant-reports-report-type-#{id}") do
      reports = []
      categories = Category.search("@report_type_id #{self.id}",limit: 5).to_a
      categories.each do |cat|
        reports << [cat,Report.search(with: {report_type_id: self.id,category_id: cat.id},sql: {order: "created_at desc"}, limit: 3).to_a]
      end
      reports
    end
  end

  def related_categories
    Rails.cache.fetch("relevant-reports-report-type--category-#{id}") do
      Category.search("@report_type_id #{self.id}").to_a.uniq
    end
  end
end

app/views/admin/reports/_update_positions.html.erb
            <input type="hidden" id="position1" name="title" class="form-control">
   


            <input type="hidden" id="position2" name="category" class="form-control">
     

            <input type="hidden" id="position3"  name="pages" class="form-control">
   

            <input type="hidden" id="position4" name="one_user_pdf" class="form-control">

            <input type="hidden"  id="position5" name="site_pdf" class="form-control">
      


            <input type="hidden" id="position6"  name="enterprise_pdf" class="form-control">
    

            <input type="hidden"  id="position7" name="publish_date" class="form-control">
      


            <input type="hidden" id="position8" name="description" class="form-control">
     

            <input type="hidden" id="position9" name="table_of_content" class="form-control">
     

            <input type="hidden" id="position10" name="publisher" class="form-control">
    

            <input type="hidden" id="position11"  name="country" class="form-control">
   

app/views/admin/reports/deactive_reports.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Reports</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Reports</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->

	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								Deactivate Reports
							</div>
						
							<div class="clearfix"></div>
						</div>



 <div id ="reports">
 

 <div class="widget-content">
							<div class="padd">

	<table class="table table-striped table-bordered table-hover">
			<thead><%= search_form_for @search, url: admin_deactive_reports_path,
                        html: { method: :post } do |f| %>
				<tr>
				<td></td>
				<td>

				  <%= f.search_field :title_cont,:class=>"form-control" %>
				</td>
				<td>
		
				  <%= f.search_field :publisher_name_cont ,:class=>"form-control"%>
				</td>
				<td>
					  <%= f.search_field :publish_month_eq ,:class=>"form-control"%>
				</td>
				<td>
			
				  <%= f.search_field :one_user_eq,:class=>"form-control"%>
				</td>

				<td>
				  <%= f.submit  :class=>"btn btn-sm btn-success" %>
				   <input type="reset" value="Reset!" class="btn btn-sm btn-default">
				</td>




				</tr><% end %>
				<tr>
					<th style="width: 5%;"><input type="checkbox" id="selectAll" value="selectAll">All</th>
				    <th style="width: 30%;" class="pretty">Report Name</th>
				    <th style="width: 20%;" class="pretty">Publisher Name</th>
				     <th style="width: 20%;" class="pretty">Publish Date</th>
				    <th style="width: 10%;" class="pretty">Price</th>
					<th style="width: 15%;" >Action</th>
				</tr>
			</thead>
			<tbody>
				<%= form_tag edit_multiple_admin_reports_path, method: :get do %>
				<% @reports.each do |report| %>
				<tr>
					<td><%= check_box_tag "report_ids[]", report.id %> </td>
				    <td><%= report.title %></td>				   
				    <td><%= report.publisher.name rescue nil %></td>				
				    <td> <%= report.publish_month.to_date.strftime("%B, %Y") rescue nil%></td>
				    <td> <i class="fa fa-usd"></i><%= report.one_user %></td>
					<td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_report_path(report) , :class=>'btn btn-xs btn-warning'  %> <a href="/admin/reports/<%= report.id %>/delete" data-confirm="Are you sure?" data-method="delete" class="btn btn-xs btn-danger" ><i class="fa fa-times"></i> </a>


					</td>
				</tr>

				<% end %>

				<tr>
				<td><%= hidden_field_tag :return_to , "deactive"%> 
					<%= submit_tag "Edit Checked", :class => 'btn btn-sm btn-default'  %> </td>
				</tr>
			<% end %>
			</tbody>
		</table>

</div>


	<div class="widget-foot">

	
	
		<div class="pull-right">

	    <%unless params[:q].present?%>
		<%= page_entries_info @reports %>	<br/><%= will_paginate @reports, renderer: BootstrapPagination::Rails %>
		<%end%>
		</div>

		<div class="clearfix"></div>

	</div>

</div>














 </div>


						
						<div class="widget-foot">
					
						

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>




<script language="Javascript" type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>
<script language="Javascript" type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script type="text/javascript">

jQuery(document).ready(function() {
	
jQuery('#q_publish_month_eq').monthpicker();
});
</script>


<script type="text/javascript">
var jq = jQuery.noConflict(); 

jq('#selectAll').click(function() {
   if(this.checked) {
       jq(':checkbox').each(function() {
           this.checked = true;                        
       });
   } else {
      jq(':checkbox').each(function() {
           this.checked = false;                        
       });
   } 
});
</script>

app/views/admin/reports/index.html.erb
<style type="text/css">
.pretty th .current {
  padding-right: 12px;
  background-repeat: no-repeat;
  background-position: right center;
}

.pretty th .asc {
  background-image: url(/assets/sort_asc.png);
}

.pretty th .desc {
  background-image: url(/assets/sort_desc.png);
}

</style>



<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Reports</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Reports</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->

	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
				<%if params[:action] == "search"%>
					<button type="button" onclick="javascript:history.back()", class="btn btn-sm btn-default">
						Back to Result
					</button>
				<%end%>
				<div class="widget">
					<div class="widget-head">
						<div class="pull-left">
							Reports
						</div>
					
						<div class="clearfix"></div>
					</div>
       <div id="reports">
		<%= hidden_field_tag :direction, params[:direction] %>
		<%= hidden_field_tag :sort, params[:sort] %>
	
		<table class="table table-striped table-bordered table-hover">
			<thead><%= form_tag admin_reports_path, :method => "GET" do |f| %>
			<thead>
				<tr>
				<td></td>
				<td>

				  <%= text_field_tag "report[title]",(params[:report][:title] rescue nil),:class=>"form-control", :placeholder=>"Report title" %>
				</td>
				<td>
		
				  <%= text_field_tag "report[publisher_name]" ,(params[:report][:publisher_name] rescue nil),:class=>"form-control", :placeholder=>"Publisher"%>
				</td>
		
				<td>
					<div class="col-md-5">
					  <%= text_field_tag "report[day]",(params[:report][:day] rescue nil),:class=>"form-control", :placeholder=>"Date"%>
					</div>
					<div class="col-sm-7">
				    <%= text_field_tag "report[publish_month]",(params[:report][:publish_month] rescue nil),:class=>"form-control", :placeholder=>"Month"%>
					</div>
				</td>
				<td>
			
				  <%= text_field_tag "report[one_user]",(params[:report][:one_user] rescue nil),:class=>"form-control", :placeholder=>"Price"%>
				</td>

				<td>
				  <%= submit_tag  "Search", :class=>"btn btn-sm btn-success",:onclick=> " return validateMonth();" %>
				   <a href="/admin/reports" class="btn btn-sm btn-default">Reset!</a>
				</td>




				</tr><% end %>
				<tr>
					<th><input type="checkbox" id="selectAll" value="selectAll">All</th>
				    <th style="width: 30%;" class="pretty">Report Name</th>
				    <th style="width: 20%;" class="pretty">Publisher Name</th>
				    <th style="width: 23%;" class="pretty">Publish Date</th>
				    <th style="width: 10%;" class="pretty">Price</th>
					<th style="width: 15%;" >Action</th>
				</tr>
			</thead>
			<tbody>
				<%= form_tag edit_multiple_admin_reports_path, method: :post do %>
			
				<tr>
				  <%if current_user.is_superadmin%>
				  <td><%= submit_tag "Edit Selected", :class => 'btn btn-sm btn-default'  %></td> <td><%= submit_tag 'Delete Selected', :class => 'btn btn-sm btn-danger' , :name => 'delete_button', :onclick=>"if(confirm('Are you sure you want to delete the selected reports?'))  return true;  else  return false;" %> </td>
				  <%end%>
				</tr>
				
				<% @reports.each do |report| %>
				<tr>
					<td><%= check_box_tag "report_ids[]", report.id %></td>
				    <td><%= report.title %></td>
				   
				    <td><%= report.publisher.name rescue nil %></td>
				     <td><%= report.day rescue nil%> <%= report.publish_month.to_date.strftime("%B, %Y") rescue nil%></td>
				    <td> <i class="fa fa-usd"></i><%= report.one_user %></td>
					<td>
						<%if current_user.is_superadmin%>
						<%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_report_path(report) , :class=>'btn btn-xs btn-warning'  %> <a href="/admin/reports/<%= report.id %>/delete" data-confirm="Are you sure?" data-method="delete" class="btn btn-xs btn-danger" ><i class="fa fa-times"></i> </a>
						<%end%>


					</td>
				</tr>

				<% end %>
				
				<tr>
					<%if current_user.is_superadmin%>
				    <td><%= submit_tag "Edit Selected", :class => 'btn btn-sm btn-default'  %></td> <td><%= submit_tag 'Delete Selected', :class => 'btn btn-sm btn-danger' , :name => 'delete_button', :onclick=>"if(confirm('Are you sure you want to delete the selected reports?'))  return true;  else  return false;" %> </td>
				    <% end %>
				</tr>
				
			<% end %>
			</tbody>
		</table>
  </div>

				
	<div class="widget-foot">

		<div class="pull-left">
			<%= link_to  "Add Report", new_admin_report_path, :class => 'btn btn-sm btn-primary' %>
			<%= link_to  "Import Report(.xlsx)", upload_reports_path, :class => 'btn btn-sm btn-primary' %>
		</div>

	
		<div class="pull-right">

	    <%unless params[:q].present?%>
		<%= page_entries_info @reports %>	<br/><%= will_paginate @reports, renderer: BootstrapPagination::Rails %>
		<%end%>
		</div>

		<div class="clearfix"></div>

	</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>



<script language="Javascript" type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>
<script language="Javascript" type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

<script type="text/javascript">

jQuery(document).ready(function() {
	
jQuery('#report_publish_month').monthpicker({pattern: 'yyyy/mm'});
});
</script>


<script type="text/javascript">
var jq = jQuery.noConflict(); 

jq('#selectAll').click(function() {
   if(this.checked) {
       jq(':checkbox').each(function() {
           this.checked = true;                        
       });
   } else {
      jq(':checkbox').each(function() {
           this.checked = false;                        
       });
   } 
});

function validateMonth(){
	if(jq("#report_day").val().length > 0 && !jq("#report_publish_month").val().length > 0){
		alert("Please select Month and Year")
		return false;
	}else{
		return true;
	}
}
</script>

app/views/admin/reports/index.js.erb
$("#reports").html("<%= escape_javascript(render("reports")) %>");